package user;

import java.util.ArrayList;
import main.Home;
import page.student.Task;
import util.Actions;
import util.Msg;

public class School {
    // list to store request generated by users
    public static ArrayList<TaskRequest> taskRequestList = new ArrayList<>();

    public static ArrayList<Task> taskList = new ArrayList<>();

    // list of members created are strored in an ArrayList for reference (not in
    // use)
    public static ArrayList<User> userList = new ArrayList<>();

    public static void viewTaskList() {
        for (Task task : taskList) {
            taskDesc(task);
        }

    }

    public static void schoolMembers() {
        Msg.border();
        System.out.println("Our Members");
        for (User user : School.userList) {
            System.out.println();
            System.out.println("Elite ID : " + user.eliteID);
            System.out.println("Name     : " + user.name);
            System.out.println("Position : " + user.position);
        }
        Actions.hold();
        Home.menu();
    }

    public static void taskDesc(Task task) {
        System.out.println();
        System.out.println("Task ID : " + task.taskID);
        System.out.println("Status : " + task.taskStatus);
        System.out.println("Task Name : " + task.taskName);
        System.out.println("Task Details : " + task.taskDetail);
        System.out.println("Task Reward : " + task.taskReward);
        System.out.println();
    }

    public static void schoolIntro() {
        Msg.header();
        System.out.println();
        System.out.println("Elite School of India");
        System.out.println("School created to create Elites");
        System.out.println();
        System.out
                .println("Objective : To provide best students best facilities irrespective of their financial status");
        System.out.println("Founder : Jspiders");
        System.out.println("co-founder : Sandip Gupta");
        System.out.println();
        Msg.border();
        System.out.print("enter 'm' to see out members or any other key to go back -> ");
        switch (Actions.inputStr()) {
            case "m":
                schoolMembers();
                break;
            default:
                Home.menu();
                break;
        }
    }

}
